applications/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", include("applications.core.urls")),
    path("services", include("applications.services.urls", namespace="services")),
    # Django Admin, use {% url 'admin:index' %}
    path("admin", admin.site.urls),
    # User management
    path("users/", include("applications.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ecliptoinc/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

ecliptoinc/templates/base.html
{% extends "layout.html" %}
{% comment %} <body class="{% block bodyclass %}{% endblock bodyclass %}">
  {% block body %}
  <div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler navbar-toggler-right"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">ecliptoinc</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link"
                   href="{% url 'users:detail' request.user.pk %}">{% translate "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
              </li>
            {% else %}
              {% if ACCOUNT_ALLOW_REGISTRATION %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                </li>
              {% endif %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class="container">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
          {{ message }}
          <button type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %}
    {% block main %}
      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
    {% endblock main %}

  </div>
  {% endblock body %}
  <!-- /container -->
  {% block modal %}
  {% endblock modal %}
  {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
    
  {% endblock inline_javascript %}
</body>
</html> {% endcomment %}

{% block body %}

{% comment %} header {% endcomment %}
{% include "components/navbar/index.html" %}

{% block main %}{% endblock main %}

{% comment %} block footer {% endcomment %}
{% include "components/footer/index.html" %}

{% endblock body %}

ecliptoinc/templates/layout.html
{% load static i18n compress%}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">

  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <title>
      {% block title %}
        Eclipto Inc
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Eclipto Inc, The best and The Biggest IT solutions website"/>
    <meta name="author" content="kwasa, daniel"/>
    <meta name="msapplication-TileColor" content="#0E0E0E">
    <meta name="template-color" content="#0E0E0E">
    <meta name="keywords" content="index, page">
    <link rel="shortcut icon" type="favicon" href="{% static 'assets/imgs/template/favicon.svg' %}">
    <link href="{% static 'assets/css/style.css' %}?v=1.0.0" rel="stylesheet">
    {% block css %}

      <!-- Your stuff: Third-party CSS libraries go here -->
      <!-- This file stores project-specific CSS -->

      {% compress css %}
      <link href="{% static 'assets/css/project.css' %}" rel="stylesheet"/>
      {% endcompress %}

    {% endblock css %}
    <!-- Le javascript ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->

      {% compress js %}
      <script src="{% static 'assets/js/dist/htmx.min.js' %}"></script>
      <script src="{% static 'assets/js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </head>

  <body class="{% block bodyclass %}{% endblock bodyclass %}">

    {% comment %} loader  {% endcomment %}
    <div id="preloader-active">
      <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
          <div class="text-center"><img src="{% static 'assets/imgs/template/loading.gif' %}" alt="Eclipto"></div>
        </div>
      </div>
    </div>


    {% comment %} body {% endcomment %}

    {% block body %}


    <main class="main">
        {% block main %}{% endblock main %}
    </main>


    {% endblock body %}

    <!-- /container -->
  {% block modal %}
  {% endblock modal %}

  {% comment %} scripts {% endcomment %}

   <!--Vendors Scripts-->
   <script src="{% static 'assets/js/vendor/jquery-3.7.0.min.js' %}"></script>
   <script src="{% static 'assets/js/vendor/jquery-migrate-3.3.0.min.js' %}"></script>
   <script src="{% static 'assets/js/vendor/bootstrap.bundle.min.js' %}"></script>
   <!--Other-->
   <script src="{% static 'assets/js/plugins/magnific-popup.js' %}"></script>
   <script src="{% static 'assets/js/plugins/perfect-scrollbar.min.js' %}"></script>
   <script src="{% static 'assets/js/plugins/swiper-bundle.min.js' %}"></script>
   <script src="{% static 'assets/js/plugins/slick.js' %}"></script>
   <script src="{% static 'assets/js/plugins/jquery.carouselTicker.js' %}"></script>
   <script src="{% static 'assets/js/plugins/masonry.min.js' %}"></script>
   <script src="{% static 'assets/js/plugins/scrollup.js' %}"></script>
   <script src="{% static 'assets/js/plugins/wow.js' %}"></script>
   <script src="{% static 'assets/js/plugins/waypoints.js' %}"></script>
   <script src="{% static 'assets/js/plugins/counterup.js' %}"></script>
   <!-- Count down-->
   <script src="{% static 'assets/js/vendor/jquery.countdown.min.js' %}"></script>
   <!--Custom script for this template-->
   <script src="{% static 'assets/js/main.js' %}?v=1.0.0"></script>
  {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
    {% endcomment %}
  {% endblock inline_javascript %}
  </body>

</html>