applications/services/urls.py
from django.urls import reverse, path, include


from . import views

app_name = "services"
urlpatterns = [
    path("", views.ServiceListView.as_view(), name="services"),
    path("/features", views.FeatureListView.as_view(), name="features"),
    path("<str:slug>/", views.ServiceView.as_view(), name="category"),
]

config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", include("applications.core.urls")),
    path("services", include("applications.services.urls", namespace="services")),
    # Django Admin, use {% url 'admin:index' %}
    path("admin", admin.site.urls),
    # User management
    path("users/", include("applications.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

applications/services/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from typing import ClassVar


class CategoryManager(models.QuerySet):

    def monthly_pricing(self):
        return self.get(category_plan__name__icontains="Monthly")

    def yearly_pricing(self):
        return self.get(category_plan__name="Y")


class AbstrDb(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(AbstrDb, self).save(*args, **kwargs)


class Category(AbstrDb):
    icon = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="category/")

    # objects: ClassVar[CategoryManager] = CategoryManager()
    objects = CategoryManager.as_manager()

    def services(self):
        return self.category_services.all()  # type: ignore

    def monthly_plan(self):
        return self.category_plan.get(name="M")  # type: ignore

    def yearly_plan(self):
        return self.category_plan.get(name="Y")  # type: ignore

    def plans(self):
        return self.category_plan.all()  # type: ignore

    def get_absolute_url(self):
        return reverse("services:category", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        return super(Category, self).save(*args, **kwargs)


# Create your models here.
class Service(AbstrDb):
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="category_services",
    )

    def save(self, *args, **kwargs):
        return super(Service, self).save(*args, **kwargs)


class ServiceVariant(AbstrDb):
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE, related_name="service_variants"
    )

    def save(self, *args, **kwargs):
        return super(ServiceVariant, self).save(*args, **kwargs)


class Plan(models.Model):
    category = models.ForeignKey(
        Category,
        related_name="category_plan",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    name = models.CharField(
        max_length=100,
        choices=(
            ("M", "Monthly"),
            ("Y", "Yearly"),
        ),
        unique=True,
        default="M",
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Plan, self).save(*args, **kwargs)

    def plan_features(self):
        return self.plan.all()  # type: ignore


class Pricing(models.Model):
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE, related_name="plan")
    package = models.CharField(
        max_length=100,
        choices=(
            ("B", "Basic"),
            ("P", "Premium"),
            ("E", "Enterprise"),
        ),
        default="B",
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    discounted_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00
    )

    def __str__(self):
        return f"{self.plan.name} {self.package}"

    def calculated_discount(self):
        return f"{int((self.discount / self.price) * 100)}"

    def features(self):
        return self.pricing.all()  # type: ignore

    def save(self, *args, **kwargs):
        if self.discount:
            self.discounted_price = self.price - self.discount
        self.discounted_price = self.price
        return super(Pricing, self).save(*args, **kwargs)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=("plan", "package"),
                name="unique_pricing_plan_package",
            )
        ]


class PricingFeature(models.Model):
    pricing = models.ForeignKey(
        Pricing, related_name="pricing", on_delete=models.CASCADE
    )
    feature = models.CharField(max_length=100)

applications/services/forms.py
# from applications.core.models import RequestQuoteContact
from django import forms
from applications.services.models import Pricing  # type: ignore


class RequestQuoteContactForm(forms.ModelForm):
    package = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-control py-2 px-2",
                "style": "padding: 0.94rem 1.5rem",
            },
        ),
        choices=(
            ("B", "Basic"),
            ("P", "Premium"),
            ("E", "Enterprise"),
        ),
    )  # type: ignore

    occupation = forms.CharField(
        max_length=100, help_text="What you do, i.e., student, software developer, etc."
    )

    class Meta:
        # model = RequestQuoteContact
        fields = ["full_name", "occupation", "email", "package", "message"]

applications/services/views.py
from typing import Any
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category
from django.utils.decorators import method_decorator

# from .forms import RequestQuoteContactForm
from applications.services.models import Pricing
from django.contrib import messages
from django.http import HttpRequest, HttpResponseRedirect
from django.views.decorators.cache import cache_page

# Create your views here.
from django.shortcuts import render
from django.views.generic import TemplateView


class CachedPageViewMixin(TemplateView):
    @method_decorator(cache_page(60 * 60 * 24))
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        return super().dispatch(request, *args, **kwargs)


class ServiceListView(CachedPageViewMixin):
    template_name = "pages/services.html"


class ServiceView(CachedPageViewMixin):
    category = Category
    template_name = "pages/service.html"
    # form_class = RequestQuoteContactForm

    def get_object(self, **kwargs):
        return get_object_or_404(self.category, slug=kwargs.get("slug"))

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["category"] = self.get_object(**kwargs)
        context["form"] = self.form_class()
        return context


class FeatureListView(CachedPageViewMixin):
    template_name = "pages/features.html"

ecliptoinc/templates/components/Home/case.html
{% load static %}

<section class="section-box box-preparing">
  <div class="box-preparing-inner">
    <div class="container">
      <div class="text-start">
        <div class="internet-icon">
          <span></span>
          Our Portfolio</div>
        <h2 class="heading-2 mb-20">We Provide Truly Prominent IT Solutions</h2>
        <p class="text-lg">Nivia is an independent web design studio with a rich history. Founded in 1999, it gathered the best web designers &amp; developers.</p>
        <div class="box-button-preparing">
          <ul class="nav nav-tabs justify-content-start" role="tablist">
            <li>
              <a class="btn btn-neutral-100" href="#tab-1" data-bs-toggle="tab" role="tab" aria-controls="tab-1" aria-selected="true">IT Management</a>
            </li>
            <li>
              <a class="btn btn-neutral-100" href="#tab-2" data-bs-toggle="tab" role="tab" aria-controls="tab-2" aria-selected="false">Data Security</a>
            </li>
            <li>
              <a class="btn btn-neutral-100" href="#tab-3" data-bs-toggle="tab" role="tab" aria-controls="tab-2" aria-selected="false">Business Reform</a>
            </li>
            <li>
              <a class="btn btn-neutral-100" href="#tab-4" data-bs-toggle="tab" role="tab" aria-controls="tab-2" aria-selected="false">Firewall Advancement</a>
            </li>
            <li>
              <a class="btn btn-neutral-100" href="#tab-5" data-bs-toggle="tab" role="tab" aria-controls="tab-2" aria-selected="false">Infrastructure Plan</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="block-group-preparing">
        <div class="tab-content">
          <div class="tab-pane fade active show" id="tab-1">
            <div class="item-preparing">
              <div class="item-preparing-left"></div>
              <div class="item-preparing-right">
                <div class="internet-icon">
                  <span></span>
                  Our Features</div>
                <h2 class="heading-2 mb-20">Trusted by worldwide clients since 1980</h2>
                <p class="text-lg neutral-700">In a professional context it often happens that private or corporate clients order a publication news while still not being ready. In a professional context it often happens that private or corporate clients order a publication news while still not being ready.</p>
                <div class="box-list-check">
                  <ul class="list-check">
                    <li>Trustworthy Research</li>
                    <li>SEO Efficiency</li>
                    <li>Time Efficiency</li>
                    <li>Smart Installation Tools</li>
                    <li>Dynamic Boosting</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="tab-2">
            <div class="item-preparing">
              <div class="item-preparing-left img-2"></div>
              <div class="item-preparing-right">
                <div class="internet-icon">
                  <span></span>
                  Our Features</div>
                <h2 class="heading-2 mb-20">Trusted by worldwide clients since 1980</h2>
                <p class="text-lg neutral-700">In a professional context it often happens that private or corporate clients order a publication news while still not being ready. In a professional context it often happens that private or corporate clients order a publication news while still not being ready.</p>
                <div class="box-list-check">
                  <ul class="list-check">
                    <li>Trustworthy Research</li>
                    <li>SEO Efficiency</li>
                    <li>Time Efficiency</li>
                    <li>Smart Installation Tools</li>
                    <li>Dynamic Boosting</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="tab-3">
            <div class="item-preparing">
              <div class="item-preparing-left img-3"></div>
              <div class="item-preparing-right">
                <div class="internet-icon">
                  <span></span>
                  Our Features</div>
                <h2 class="heading-2 mb-20">Trusted by worldwide clients since 1980</h2>
                <p class="text-lg neutral-700">In a professional context it often happens that private or corporate clients order a publication news while still not being ready. In a professional context it often happens that private or corporate clients order a publication news while still not being ready.</p>
                <div class="box-list-check">
                  <ul class="list-check">
                    <li>Trustworthy Research</li>
                    <li>SEO Efficiency</li>
                    <li>Time Efficiency</li>
                    <li>Smart Installation Tools</li>
                    <li>Dynamic Boosting</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="tab-4">
            <div class="item-preparing">
              <div class="item-preparing-left img-4"></div>
              <div class="item-preparing-right">
                <div class="internet-icon">
                  <span></span>
                  Our Features</div>
                <h2 class="heading-2 mb-20">Trusted by worldwide clients since 1980</h2>
                <p class="text-lg neutral-700">In a professional context it often happens that private or corporate clients order a publication news while still not being ready. In a professional context it often happens that private or corporate clients order a publication news while still not being ready.</p>
                <div class="box-list-check">
                  <ul class="list-check">
                    <li>Trustworthy Research</li>
                    <li>SEO Efficiency</li>
                    <li>Time Efficiency</li>
                    <li>Smart Installation Tools</li>
                    <li>Dynamic Boosting</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="tab-5">
            <div class="item-preparing">
              <div class="item-preparing-left img-5"></div>
              <div class="item-preparing-right">
                <div class="internet-icon">
                  <span></span>
                  Our Features</div>
                <h2 class="heading-2 mb-20">Trusted by worldwide clients since 1980</h2>
                <p class="text-lg neutral-700">In a professional context it often happens that private or corporate clients order a publication news while still not being ready. In a professional context it often happens that private or corporate clients order a publication news while still not being ready.</p>
                <div class="box-list-check">
                  <ul class="list-check">
                    <li>Trustworthy Research</li>
                    <li>SEO Efficiency</li>
                    <li>Time Efficiency</li>
                    <li>Smart Installation Tools</li>
                    <li>Dynamic Boosting</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

ecliptoinc/templates/components/Home/clients.html
{% load static %}

<section class="section-box wow animate__animated animate__fadeIn box-logos-2">
  <div class="container">
    <div class="carouselTickerLogos2 carouselTicker_vertical" id="slide-logos">
      <ul class="carouselTicker__list list-logos">
        <li class="carouselTicker__item">
          <div class="item-logo"><img src="{% static 'assets/imgs/page/homepage3/logo1.png' %}" alt="Eclipto"></div>
        </li>
        <li class="carouselTicker__item">
          <div class="item-logo"><img src="{% static 'assets/imgs/page/homepage3/logo2.png' %}" alt="Eclipto"></div>
        </li>
        <li class="carouselTicker__item">
          <div class="item-logo"><img src="{% static 'assets/imgs/page/homepage3/logo3.png' %}" alt="Eclipto"></div>
        </li>
        <li class="carouselTicker__item">
          <div class="item-logo"><img src="{% static 'assets/imgs/page/homepage3/logo4.png' %}" alt="Eclipto"></div>
        </li>
        <li class="carouselTicker__item">
          <div class="item-logo"><img src="{% static 'assets/imgs/page/homepage3/logo5.png' %}" alt="Eclipto"></div>
        </li>
        <li class="carouselTicker__item">
          <div class="item-logo"><img src="{% static 'assets/imgs/page/homepage3/logo6.png' %}" alt="Eclipto"></div>
        </li>
        <li class="carouselTicker__item">
          <div class="item-logo"><img src="{% static 'assets/imgs/page/homepage3/logo7.png' %}" alt="Eclipto"></div>
        </li>
        <li class="carouselTicker__item">
          <div class="item-logo"><img src="{% static 'assets/imgs/page/homepage3/logo8.png' %}" alt="Eclipto"></div>
        </li>
        <li class="carouselTicker__item">
          <div class="item-logo"><img src="{% static 'assets/imgs/page/homepage3/logo9.png' %}" alt="Eclipto"></div>
        </li>
        <li class="carouselTicker__item">
          <div class="item-logo"><img src="{% static 'assets/imgs/page/homepage3/logo1.png' %}" alt="Eclipto"></div>
        </li>
      </ul>
    </div>
  </div>
</section>

ecliptoinc/templates/components/Home/faqs.html
{% load static %}
<section class="section-box box-faqs-3">
  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <div class="box-faq-left">
          <a class="btn btn-brand-4-sm" href="#">Frequently Asked Questions</a>
          <h2 class="heading-2 mb-20 mt-20">Do you have any questions?</h2>
          <p class="text-lg neutral-700">Below you’ll find answers to the most common questions you may have on Nivia Platform & Online Advertising. Also, please feel free to check out our Facebook & Google Advertising Guides & Academy. If you still can’t find the answer you’re looking for, just
            <a class="text-18-bold brand-1-1" href="#">Contact us</a>
          </p>
        </div>
      </div>
      <div class="col-lg-7">
        <div class="accordion accordion-flush accordion-style-2" id="accordionFAQS">
          <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingOne">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">What audiences can I target when creating my Facebook campaigns?</button>
            </h2>
            <div class="accordion-collapse collapse show" id="flush-collapseOne" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFAQS">
              <div class="accordion-body">
                <p>Discover what sets this apart as the market's easiest and most powerful video interviewing platform, and why hiring managers consistently choose us over the competition. Discover what sets this apart as the market's easiest and most powerful video interviewing platform, and why hiring managers consistently choose us over the competition</p>
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">Can you provide benchmarks for Facebook advertising costs?</button>
            </h2>
            <div class="accordion-collapse collapse" id="flush-collapseTwo" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFAQS">
              <div class="accordion-body">Discover what sets this apart as the market's easiest and most powerful video interviewing platform, and why hiring managers consistently choose us over the competition. Discover what sets this apart as the market's easiest and most powerful video interviewing platform, and why hiring managers consistently choose us over the competition</div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingThree">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">Where will my Google Ads be shown?</button>
            </h2>
            <div class="accordion-collapse collapse" id="flush-collapseThree" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFAQS">
              <div class="accordion-body">Discover what sets this apart as the market's easiest and most powerful video interviewing platform, and why hiring managers consistently choose us over the competition. Discover what sets this apart as the market's easiest and most powerful video interviewing platform, and why hiring managers consistently choose us over the competition</div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingFour">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">Which keywords should I use for my Google Ads campaigns?</button>
            </h2>
            <div class="accordion-collapse collapse" id="flush-collapseFour" aria-labelledby="flush-headingFour" data-bs-parent="#accordionFAQS">
              <div class="accordion-body">Discover what sets this apart as the market's easiest and most powerful video interviewing platform, and why hiring managers consistently choose us over the competition. Discover what sets this apart as the market's easiest and most powerful video interviewing platform, and why hiring managers consistently choose us over the competition</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

ecliptoinc/templates/components/Home/hero.html
{% load static %}

<section class="section-box">
  <div class="banner-hero hero-5">
    <div class="banner-image-main">
      <div class="img-bg"></div>
      <div class="blur-bg blur-move"></div>
    </div>
    <div class="banner-inner-top">
      <div class="container">
        <div class="box-banner-left">
          <a class="btn btn-brand-5-new mb-20" href="{% url 'careers' %}">
            <span>New</span>We're are hiring
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewbox="0 0 22 22" fill="none">
              <path d="M22 11.0003L18.4791 7.47949V10.3074H0V11.6933H18.4791V14.5213L22 11.0003Z" fill=""></path>
            </svg>
          </a>
          {% comment %} <h1 class="display-2 mb-30 mt-25 neutral-0">Get the insights you need to improve your business</h1> {% endcomment %}
          <h1 class="display-2 mb-25 neutral-0 mt-5">Build Your <span class="text-bg-brand-4 ml-5">Dream</span> Website with Our<br class="d-none d-lg-block"> Skilled Team</h1>
          <p class="text-lg neutral-500 mb-55">Use our analytics, reporting, and AI-assisted optimization tools to monitor trends, track performance, and create better campaigns that reach more customers likely to engage and convert.</p>
          <div class="d-flex mb-60">
            <a class="hover-up mr-5" href="#"><img src="{% static 'assets/imgs/page/homepage1/googleplay.png' %}" alt="Eclipto"></a>
            <a class="hover-up" href="#"><img src="{% static 'assets/imgs/page/homepage1/appstore.png' %}" alt="Eclipto"></a>
          </div>
        </div>
      </div>
    </div>
    <br>
    <br>
    <div class="banner-inner-bottom">
      <div class="container">
        <div class="box-joined">
          <div class="box-authors">
            {% comment %} <span class="item-author"><img src="{% static 'assets/imgs/page/homepage1/author.png' %}" alt="Eclipto"></span><span class="item-author"><img src="{% static 'assets/imgs/page/homepage1/author2.png' %}" alt="Eclipto"></span><span class="item-author"><img src="{% static 'assets/imgs/page/homepage1/author3.png' %}" alt="Eclipto"></span><span class="item-author"><span class="text-num-author text-md-bold color-brand-2">+2k</span></span></div> {% endcomment %}
          {% comment %} <span class="text-lg d-inline-block">Join thousands of users in using<br class="d-none d-md-block">the Eclipto platform!</span> {% endcomment %}
        </div>
      </div>
    </div>
  </div>
</section>

ecliptoinc/templates/components/Home/index.html
{% include "components/Home/hero.html" %}

{% include "components/Home/clients.html" %}

{% include "components/Home/whyus.html" %}

{% include "components/Home/services.html" %}

{% include "components/Home/case.html" %}

{% include "components/Home/howitworks.html" %}

{% include "components/Home/testimonials.html" %}

{% include "components/Home/faqs.html" %}

ecliptoinc/templates/components/Home/whyus.html
{% load static %}

<section class="section-box wow animate__animated animate__fadeIn box-our-features-4">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 mb-40">
        <div class="internet-icon">
          <span></span>
          Our Features</div>
        <h2 class="heading-2 mb-20">Eclipto Platform - The best way to build your startup.</h2>
        <p class="text-lg neutral-700">Eclipto is an independent web design studio with a rich history. Founded in 1999, it gathered the best web designers &amp; developers.</p>
        <div class="row mt-50">
          <div class="col-lg-6 col-md-6">
            <div class="card-feature-2">
              <div class="card-image"><img src="{% static 'assets/imgs/page/homepage3/marketing.svg' %}"></div>
              <div class="card-info">
                <a href="#">
                  <h3 class="text-22-bold">Marketing Strategy</h3>
                </a>
                <p class="text-md neutral-700">Strategic approach that involves creating and distributing valuable, relevant</p>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <div class="card-feature-2">
              <div class="card-image"><img src="{% static 'assets/imgs/page/homepage3/digital.svg' %}"></div>
              <div class="card-info">
                <a href="#">
                  <h3 class="text-22-bold">Digital Services</h3>
                </a>
                <p class="text-md neutral-700">An infrastructure plan outlines a comprehensive strategy for designing, building</p>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <div class="card-feature-2">
              <div class="card-image"><img src="{% static 'assets/imgs/page/homepage3/product.svg' %}"></div>
              <div class="card-info">
                <a href="#">
                  <h3 class="text-22-bold">Product Selling</h3>
                </a>
                <p class="text-md neutral-700">Signifies the enhancement of security measures, typically through the use of advanced firewall</p>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <div class="card-feature-2">
              <div class="card-image"><img src="{% static 'assets/imgs/page/homepage3/social.svg' %}"></div>
              <div class="card-info">
                <a href="#">
                  <h3 class="text-22-bold">Social Marketing</h3>
                </a>
                <p class="text-md neutral-700">Involves overseeing an organization's technology resources, including hardware, software, networks</p>
              </div>
            </div>
          </div>
        </div>
        <div class="box-buttons-feature-4">
          <a class="btn btn-black" href="{% url 'contact' %}">Get a Quote
            <svg width="22" height="8" viewbox="0 0 22 8" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M22 3.99934L18.4791 0.478516V3.30642H0V4.69236H18.4791V7.52031L22 3.99934Z" fill=""></path>
            </svg>
          </a>
          <a class="btn btn-learmore-2" href="{% url 'services:features' %}">
            <span>
              <svg width="13" height="13" viewbox="0 0 13 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                <g clip-path="url(#clip0_24_999)">
                  <path d="M10.6557 3.81393L1.71996 12.7497L0.251953 11.2817L9.18664 2.34592H1.31195V0.269531H12.7321V11.6897H10.6557V3.81393Z" fill="#191919"></path>
                </g>
                <defs>
                  <clippath id="clip0_24_999">
                    <rect width="13" height="13" fill="white"></rect>
                  </clippath>
                </defs>
              </svg>
            </span>
            Learn More</a>
        </div>
      </div>
      <div class="col-lg-6 mb-40">
        <div class="image-feature-2"><img src="{% static 'assets/imgs/page/homepage3/img-feature.png' %}" alt="Eclipto">
          <div class="card-number-feature card-number-bottom">
            <h4>
              <span class="count">17</span><span>k+</span></h4>
            <p class="text-sm">Happy Clients</p>
          </div>
          <div class="card-number-feature card-number-top">
            <h4>
              <span class="count">12</span><span>k+</span></h4>
            <p class="text-sm">Completed Cases</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>